### ISSUE TITLE
Automation of Airship/Blimp

### ISSUE THREAD

**Issue by mishraiitm** [BeaglePilot/beaglepilot#11]
Can beagle-pilot be customized for airships?I mean can we change the dynamics that define my airship in this board,If so how?I am seriously looking to buy this board!

**Comment by vmayoral** [comment]
Hello @mishraiitm, BeaglePilot efforts were integrated in ArduPilot. Refer to github.com/ardupilot/ardupilot for the main source code. As for whether or not it has support for customized airships, indeed it does. Refer to the following threads to know more about the topic:
- http://diydrones.com/profiles/blog/show?id=705844%3ABlogPost%3A44817
- http://diydrones.com/forum/topics/opensource-airship-uav-platform-silent-runner
- http://diydrones.com/forum/topics/200-indoor-autonomous-blimp

**Comment by mishraiitm** [comment]
Thanks a lot @vmayoral vmayoral! The thing is my blimp is a bit bigger,and my requirement is that the controller should be able to accommodate 8 differential equations that describe the vehicle dynamics.I have already done my simulations on matlab.I was looking for a linux based board to implement the controls. I have worked on raspberry pi,but sadly it is not real-time!
